version: '3'
services:
  mysql:
    image: mysql-test
    build: ./
    container_name: mysql-test
    expose:
    - 3300
    ports:
    - 3300:3300
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test-db
    tty: True